// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocnvnsizkntlreretxrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jbnZuc2l6a250bHJlcmV0eHJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1Mzg2MTUsImV4cCI6MjA3MzExNDYxNX0.Y8vWXpkJP1m9i2UgigRD0Yd_xNQmQ7B9pIuvz3P1_rg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});